spring.application.name=jpa10926

# at present we will not use this 
# for configuration purposes.

# as we are using spring;

# eventhough we installed spring boot ,
# but we will use context configuration instead.